name: Build V8

on: push

jobs:
  for_linux:
    name: Build v8 on linux
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        include:
          - compiler: gcc
            version: 7
            cc: gcc-7
            cxx: g++-7
            libcxx: libstdc++
          - compiler: gcc
            version: 8
            cc: gcc-8
            cxx: g++-8
            libcxx: libstdc++
          - compiler: gcc
            version: 9
            cc: gcc-9
            cxx: g++-9
            libcxx: libstdc++
          - compiler: clang
            version: '6.0'
            cc: clang-6.0
            cxx: clang++-6.0
            libcxx: libc++
          - compiler: clang
            version: '7.0'
            cc: clang-7
            cxx: clang++-7
            libcxx: libc++
          - compiler: clang
            version: 8
            cc: clang-8
            cxx: clang++-8
            libcxx: libc++
    env:
      COMPILER_NAME: ${{ matrix.compiler }}
      COMPILER_VERSION: ${{ matrix.version }}
      CC: ${{ matrix.cc }}
      CXX: ${{ matrix.cxx }}
      LIBCXX: ${{ matrix.libcxx }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: '3.7' 
          architecture: 'x64'

      - name: Find python
        id: find_python
        run: |
          echo "::set-output name=python::$(which python)"

      - name: Install compiler
        run: |
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test
          wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
          sudo apt-add-repository "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic main"
          sudo apt-get update
          sudo apt-get install -y -qq --no-install-recommends ${{ matrix.cc }} ${{ matrix.cxx }}

      - name: Install dependencies
        run: .ci/install_linux_deps.sh

      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: 3.7

      - name: Setup conda
        run: |
          conda config --set always_yes yes --set changeps1 no
          conda update -q conda
          conda info -a
          conda init bash
          conda create -y -n build-v8 python=2.7

      - name: Build V8
        shell: bash -l {0}
        run: |
          conda activate build-v8
          ${{ steps.find_python.outputs.python }} build.py

  for_macos:
    name: Build v8 on MacOS
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: .ci/install_macos_deps.sh

      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: 3.7

      - name: Setup conda
        run: |
          conda config --set always_yes yes --set changeps1 no
          conda update -q conda
          conda info -a
          conda init bash
          conda create -y -n build-v8 python=2.7

      - name: Build V8
        shell: bash -l {0}
        run: |
          conda activate build-v8
          conan create . altairwei/testing --build missing
  
  for_windows:
    name: Build v8 on Windows
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: '3.7' 
          architecture: 'x64'

      - name: Install Conan
        run: |
          pip3 install wheel setuptools
          pip3 install conan --upgrade
          pip3 install conan_package_tools bincrafters_package_tools
          conan user

      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: 3.7

      - name: Setup conda
        run: |
          conda config --set always_yes yes --set changeps1 no
          conda update -q conda
          conda info -a
          conda init powershell
          conda create -y -n build-v8 python=2.7

      - name: Build V8
        shell: powershell
        run: |
          conda activate build-v8
          conan create . altairwei/testing --build missing
